### ISSUE TITLE
`sr3d convert` include files

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sr3_tools#15]
I realized I don't know how `sr3 convert` handles include files, and `sr3d convert` definitely just ignores them. 

This should be fixed - if `sr3 convert` converts include files, then `sr3d` needs to be updated to copy those converted include files to the workstation so they can be committed.

if `sr3 convert` ignores include files, we should figure out how we want to handle include files.

**Comment by andreleblanc11** [comment]
It looks like it does include `.inc` files

https://github.com/MetPX/sarracenia/blob/efe074b5d5fbdb09465a31bda9fdb08ee27aba86/sarracenia/sr.py#L2592-L2599

**Comment by andreleblanc11** [comment]
I just did a test and it worked.

**Comment by reidsunderland** [comment]
I guess I'll need to parse the output and look for those messages

**Comment by reidsunderland** [comment]
I misread, I thought it automatically converted include files when given a .conf file that included something. But you passed an include file as input.
