### ISSUE TITLE
How to manage configs on systems that don't have access to the Git repo?

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sr3_tools#17]
We need a way to push the repo to the nodes instead of having the nodes pull it. Maybe using rsync/scp?

This could also be used as a fallback method when the Git server is down.

Ideally a completely clean repo would be pushed out with only the main branch. Any local branches should be ignored.

**Comment by petersilva** [comment]
why is this needed?

**Comment by petersilva** [comment]
ok, makes sense... other possibilities:
* for apt/dpkg and friends one can put proxies when needed to avoid push... 
* have a separate repo per zone, so that the management node and the cluster are in the same zone.
  (aka a DMZ config management node...)

Not saying they are better... just exploring the solution space.   push does feel like a better answer to me also.

**Comment by petersilva** [comment]
would you use commit hooks on gitlab to push?

**Comment by reidsunderland** [comment]
yeah, I think a separate repo would be ideal for this case, for improved security. 

A proxy might be good, since we can currently run commands on the DMZ nodes with sr3_tools. It just expects the nodes themselves to be able to pull from GitLab. We could set it up and tear it down each time.

A commit hook/GitLab pipeline could also work.

**Comment by petersilva** [comment]
so if we put a separate repo in the DMZ beside these systems, then this issue becomes unnecessary ?

**Comment by reidsunderland** [comment]
Yes

**Comment by reidsunderland** [comment]
This is solved by adding support for a "pre pull" script to "sr3_pull". It can run any script before pulling the repos, which can be used to set up a proxy/tunnel or something else to allow access to the Git server. 

I initially thought the solution to this issue might also solve the problem where configs can't be managed if the Git server is offline, but this solution doesn't accomplish that. I'll create a separate issue.
