### ISSUE TITLE
sr3_ssh accept numerical argument for node number...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sr3_tools#19]
I have a hard time remembering node names (seen a lot of clusters in my day. ;-) so I have this consistent pattern, I do:

```

sr3l uname -a


```
to get the node names, and then do sr3_ssh and use the hostname i get from that to pick a node to log into.  I was thinking... I don't actually care what the hostnames are... I would much prefer it if I could just pick the first node with:
```

sr3_ssh 1


```

and not have to enter the actual hostname of the first node. it could just iterate through the dsh configs...

**Comment by reidsunderland** [comment]
I added this, i hope it works. You have to use `-n`, like `sr3_ssh -n1`.

If you use a number greater than the number of nodes in the cluster, it will just use the last node.

**Comment by petersilva** [comment]
If there is a cluster with only nodes 9 and 10... What happens sr3_ssh -n 1

**Comment by reidsunderland** [comment]
`-n1` should connect to node 9, assuming the machine list is:

```
node9
node10
```

It's just using `head -nN | tail -n1`: 
https://github.com/MetPX/sr3_tools/blob/9ec3a3e0e13eb594779f124047cf0f4f84fca6ea/bin/sr3_ssh#L40

**Comment by reidsunderland** [comment]
I changed `-n` to `-nn`, because `-n` is a valid argument for SSH and we're actually using it in a script.
