### ISSUE TITLE
What should the workflow for removing a config be?

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sr3_tools#6]
The proper procedure for removing a config using sr3_tools isn't clear.

**Comment by petersilva** [comment]
to remove > 1 config requires the --dangerWillRobinson flag... fwiw...

**Comment by reidsunderland** [comment]
Added support for `--dangerWillRobinson` with https://github.com/MetPX/sr3_tools/commit/72c62b83cc2d4689ae042ad63923886ada6215f6

if the user doesn't specify `--dangerWillRobinson`, it still runs the remove on the nodes, where sr3 gives an error.

```
$ sr3d remove flow/hydro_quebec_http shovel/copy_ALPHA
dev01:
dev01: 2023-10-18 17:21:05,448 64002 [ERROR] root remove specify --dangerWillRobinson to remove > 1 config at a time
dev02: 2023-10-18 17:21:06,777 27309 [ERROR] root remove specify --dangerWillRobinson to remove > 1 config at a time
dev02:
```

**Comment by reidsunderland** [comment]
This is done. `sr3d remove ...` works, including with --dangerWillRobinson
