### ISSUE TITLE
sr3d not working when only options specified

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sr3_tools#9]
How to replicate

Run `sr3d` without any commands, only options

```
sr3d --version
Could not determine which argument contained the action.
Actions are: cleanup declare disable enable list remove restart run sanity setup show start status stop
```

It only doesn't work when no argument is specified

```
sr3d --logStdout status
````

The command above works.

**Comment by andreleblanc11** [comment]
`sr3d --version status` also works

**Comment by petersilva** [comment]
umm... should sr3 have a default action, that is just "status" ... or should it dump a usage... what's least surprising?

**Comment by reidsunderland** [comment]
it currently dumps the usage, I think it makes sense to keep that. `sr3d` needs to be updated to allow using `--something` options when no action is specified. I think the only options that makes sense without an action are `-v`/`--version` and `-h/--help`?
